### ISSUE TITLE
Provided adapter class does not exist

### ISSUE THREAD

**Issue by theraw** [apioo/fusio-adapter-memcache#1]
hello,

i tried to install this, but when i tried to execute `php bin/fusio system:register Fusio\Adapter\Memcache\Adapter` i got this error `Provided adapter class does not exist` (i already installed it)

Are those adapters ready for usage? or i'm doing something wrong

**Comment by chriskapp** [comment]
Hi, yes so depending on your OS you might need to add quotes around the adapter name i.e.:
`php bin/fusio system:register "Fusio\Adapter\Memcache\Adapter"`

**Comment by theraw** [comment]
`"Registration successful"`
Thank you alot
